"""Change preview_json to JSON type

Revision ID: 5a4b1818906b
Revises: 
Create Date: 2025-11-16 12:49:56.383396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4b1818906b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsed_fragments', 'preview_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='preview_json::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsed_fragments', 'preview_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using='preview_json::text')
    # ### end Alembic commands ###
